# Lab 2 - Linear Algebra

In [1]:
from mpl_toolkits.mplot3d import Axes3D

import numpy as np
import matplotlib.pyplot as plt

# fix random seed for reproducibility
np.random.seed(7131)

# matplotlib magic for inline plot
%matplotlib inline

### Linear algebra basics

In [4]:
# a scalar is a single number
scalar = 10.0
np.isscalar(scalar)

True

In [7]:
# a vector is 1D
v = np.arange(5)
print(v)

[0 1 2 3 4]


In [9]:
# while a matrix is 2D
matrix = np.arange(6).reshape(2,3)
print(matrix)

[[0 1 2]
 [3 4 5]]


In [13]:
# tensors have higher number of dimensions
tensor = np.arange(27).reshape(3,3,3)
print(tensor)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [38]:
# generate two random matices
A = np.random.random_sample((4, 3))
B = np.random.random_sample((3,2))
print(A)
print('')
print(B)

[[ 0.1948294   0.18694484  0.29809353]
 [ 0.53915291  0.00382536  0.8710852 ]
 [ 0.22093992  0.53149704  0.29688214]
 [ 0.4832809   0.80484005  0.97636989]]

[[ 0.58178275  0.65085588]
 [ 0.89260795  0.6131198 ]
 [ 0.27797347  0.18398957]]


In [39]:
# find tranpose of matrix A
np.transpose(A)

array([[ 0.1948294 ,  0.53915291,  0.22093992,  0.4832809 ],
       [ 0.18694484,  0.00382536,  0.53149704,  0.80484005],
       [ 0.29809353,  0.8710852 ,  0.29688214,  0.97636989]])

In [40]:
# dot product
np.dot(A,B)

array([[ 0.36307893,  0.29627154],
       [ 0.55922298,  0.51352684],
       [ 0.68548288,  0.52429462],
       [ 1.27097604,  0.98765145]])

In [41]:
# you can also calculate it this way
A.dot(B)

array([[ 0.36307893,  0.29627154],
       [ 0.55922298,  0.51352684],
       [ 0.68548288,  0.52429462],
       [ 1.27097604,  0.98765145]])

In [60]:
# note that np.matrix has special operators like '*' (matrix mult.)
matrix1 = np.matrix([[1,5],[5,9]])
matrix2 = np.matrix([[9,3,0],[2,1,1]])

matrix1*matrix2

matrix([[19,  8,  5],
        [63, 24,  9]])

In [49]:
# This will probably be inefficient, but manually create a function to 
# multipy two matrices

def matrix_mult(a, b):
    # check matrices are of correct dimensions
    if a.shape[1] != b.shape[0]:
        return 'invalid dimensions: must be (m x n) (n x p)'
    # create results matrix to store values
    results = np.zeros((a.shape[0], b.shape[1]))
    # calcualte matrix multiplication
    # rows in a
    for i in np.arange(a.shape[0]):
        # cols in b
        for j in np.arange(b.shape[1]):
            # rows in b
            for k in np.arange(b.shape[0]):
                results[i][j] += a[i][k]*b[k][j]
    return results         

In [48]:
matrix_mult(A,B)

array([[ 0.36307893,  0.29627154],
       [ 0.55922298,  0.51352684],
       [ 0.68548288,  0.52429462],
       [ 1.27097604,  0.98765145]])

Check you get the same result

In [50]:
np.allclose( np.dot(A,B), matrix_mult(A,B))

True

### System of equations

Solve for X in AX = B, where

\begin{equation*}
A =  \begin{vmatrix}
14 &  1\\
5 &  8
\end{vmatrix}
\end{equation*}

\begin{equation*}
X =  \begin{vmatrix}
a \\
b
\end{vmatrix}
\end{equation*}

\begin{equation*}
B =  \begin{vmatrix}
20\\
100
\end{vmatrix}
\end{equation*}

-------------------

Let's try this by finding the inverse of A. And for fun, let's define a function to find the inverse. The inverse of 2x2 matrix 
\begin{equation*}
A = \begin{vmatrix}
a &  b\\
c &  d
\end{vmatrix}
\end{equation*} 

that has a non-zero determinant, can be obtained via

\begin{equation*}
A^{-1} = \frac{1}{det(A)} \begin{vmatrix}
d &  -b\\
-c &  a
\end{vmatrix}
\end{equation*}

In [94]:
# matrix inverse for 2x2 matrix
def matrix_inverse(a):
    # check matrix is invertible, check input is a 2x2 matrix
    # return error message otherwise
    if np.linalg.det(a) == 0:
        return 'determinant of matrix is 0; matrix is non-invertible'
    if (a.shape[0] != 2) & (a.shape[1] != 2):
        return 'This is not a 2x2 matrix'
    #create results matrix to store values
    results = np.zeros((2,2))
    # interchange diagonal elements, take (-)ve of off-diagonal values
    for i in np.arange(2):
        results[i][i] = a[(i+1)%2][(i+1)%2]
        results[i][(i+1)%2] = -a[i][(i+1)%2]
    # multiply 1/determinate
    results = (1/np.linalg.det(a))*results 
    return results 

In [99]:
# define A and B matrices
A = np.array([[14, 1],[5,8]])
B = np.array([[20],[100]])

# find inverse of A using above function 
A_inverse = matrix_inverse(A)

# solve for X
X = A_inverse.dot(B)

print(X)

[[  0.56074766]
 [ 12.14953271]]


In [100]:
# we can also do this in one line using solve
print(np.linalg.solve(A,B))

[[  0.56074766]
 [ 12.14953271]]
